export { default as Header } from './Header'
export { default as Intro} from './Intro'
export { default as Advert} from './Advert'
export { default as Footer} from './Footer'
export { default as ArticleList } from './ArticleList'

export { default as Banner_Dc } from './music/Discovery/Banner'
export { default as MusicRecommand_Dc } from './music/Discovery/Recommand'
export { default as LastestMusic_Dc } from './music/Discovery/Lastest'
export { default as MvDiscovery_Dc } from './music/Discovery/MvDiscovery'
export { default as MusicDiscovery } from './music/Discovery/Discovery'
export { default as QualityRecommand } from './music/QualityRecommand'